# Generated by Django 6.0.1 on 2026-02-02 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_pendinguser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PendingUser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
    ]
